<a href="https://colab.research.google.com/github/ZuriAnahi/CifradoCesarAct2/blob/main/TitanicTarea.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
url ='https://raw.githubusercontent.com/Angel07fco/repo-bd/main/PRACTICAS/datasets/Titanic-Dataset.csv'
df = pd.read_csv(url)
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [ ]:
df['Age'].value_counts()

Age
24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [ ]:
df['Cabin'].value_counts()

Cabin
B96 B98        4
G6             4
C23 C25 C27    4
C22 C26        3
F33            3
              ..
E34            1
C7             1
C54            1
E36            1
C148           1
Name: count, Length: 147, dtype: int64

In [ ]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
valor_Nuevo = df['Age'].mode()[0]
df['Age']= df['Age'].fillna(valor_Nuevo)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df['Cabin']= df['Cabin'].fillna('No conocido')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
valor_Nuevo = df['Embarked'].mode()[0]
df['Embarked']= df['Embarked'].fillna(valor_Nuevo)
df.info()
valor_Nuevo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

'S'

In [ ]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,No conocido,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,No conocido,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,No conocido,S
5,6,0,3,"Moran, Mr. James",male,24.0,0,0,330877,8.4583,No conocido,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,No conocido,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,No conocido,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,No conocido,C

In [ ]:
df['Embarked'].value_counts()

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [ ]:
df['Cabin'].value_counts()

Cabin
No conocido    687
C23 C25 C27      4
G6               4
B96 B98          4
C22 C26          3
              ...
E34              1
C7               1
C54              1
E36              1
C148             1
Name: count, Length: 148, dtype: int64

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
# Ajustar y transformar la columna 'Name' con LabelEncoder
df['Name'] = encoder.fit_transform(df[['Name']])# Mostrar el DataFrame con la columna 'Name' transformada
df['Name'].unique()
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108.0,male,22.0,1,0,A/5 21171,7.2500,No conocido,S
1,2,1,1,190.0,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,353.0,female,26.0,0,0,STON/O2. 3101282,7.9250,No conocido,S
3,4,1,1,272.0,female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,15.0,male,35.0,0,0,373450,8.0500,No conocido,S

In [ ]:
df = pd.get_dummies(df, columns=['Sex'], dtype=int)
df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_female,Sex_male
0,1,0,3,108.0,22.0,1,0,A/5 21171,7.2500,No conocido,S,0,1
1,2,1,1,190.0,38.0,1,0,PC 17599,71.2833,C85,C,1,0
2,3,1,3,353.0,26.0,0,0,STON/O2. 3101282,7.9250,No conocido,S,1,0
3,4,1,1,272.0,35.0,1,0,113803,53.1000,C123,S,1,0
4,5,0,3,15.0,35.0,0,0,373450,8.0500,No conocido,S,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,548.0,27.0,0,0,211536,13.0000,No conocido,S,0,1
887,888,1,1,303.0,19.0,0,0,112053,30.0000,B42,S,1,0
888,889,0,3,413.0,24.0,1,2,W./C. 6607,23.4500,No conocido,S,1,0
889,890,1,1,81.0,26.0,0,0,111369,30.0000,C148,C,0,1
890,891,0,3,220.0,32.0,0,0,370376,7.7500,No conocido,Q,0,1

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
# Ajustar y transformar la columna 'Name' con LabelEncoder
df['Ticket'] = encoder.fit_transform(df[['Ticket']])# Mostrar el DataFrame con la columna 'Name' transformada
df['Ticket'].unique()
df.head(5)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_female,Sex_male
0,1,0,3,108.0,22.0,1,0,523.0,7.2500,No conocido,S,0,1
1,2,1,1,190.0,38.0,1,0,596.0,71.2833,C85,C,1,0
2,3,1,3,353.0,26.0,0,0,669.0,7.9250,No conocido,S,1,0
3,4,1,1,272.0,35.0,1,0,49.0,53.1000,C123,S,1,0
4,5,0,3,15.0,35.0,0,0,472.0,8.0500,No conocido,S,0,1

In [ ]:
##df = pd.get_dummies(df, columns=['Embarked'], dtype=int)
##df
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
# Ajustar y transformar la columna 'Name' con LabelEncoder
df['Embarked'] = encoder.fit_transform(df[['Embarked']])# Mostrar el DataFrame con la columna 'Name' transformada
df['Embarked'].unique()
df.head(5)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_female,Sex_male
0,1,0,3,108.0,22.0,1,0,523.0,7.2500,No conocido,2.0,0,1
1,2,1,1,190.0,38.0,1,0,596.0,71.2833,C85,0.0,1,0
2,3,1,3,353.0,26.0,0,0,669.0,7.9250,No conocido,2.0,1,0
3,4,1,1,272.0,35.0,1,0,49.0,53.1000,C123,2.0,1,0
4,5,0,3,15.0,35.0,0,0,472.0,8.0500,No conocido,2.0,0,1

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
# Ajustar y transformar la columna 'Name' con LabelEncoder
df['Cabin'] = encoder.fit_transform(df[['Cabin']])# Mostrar el DataFrame con la columna 'Name' transformada
df['Cabin'].unique()
df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_female,Sex_male
0,1,0,3,108.0,22.0,1,0,523.0,7.2500,146.0,2.0,0,1
1,2,1,1,190.0,38.0,1,0,596.0,71.2833,81.0,0.0,1,0
2,3,1,3,353.0,26.0,0,0,669.0,7.9250,146.0,2.0,1,0
3,4,1,1,272.0,35.0,1,0,49.0,53.1000,55.0,2.0,1,0
4,5,0,3,15.0,35.0,0,0,472.0,8.0500,146.0,2.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,548.0,27.0,0,0,101.0,13.0000,146.0,2.0,0,1
887,888,1,1,303.0,19.0,0,0,14.0,30.0000,30.0,2.0,1,0
888,889,0,3,413.0,24.0,1,2,675.0,23.4500,146.0,2.0,1,0
889,890,1,1,81.0,26.0,0,0,8.0,30.0000,60.0,0.0,0,1
890,891,0,3,220.0,32.0,0,0,466.0,7.7500,146.0,1.0,0,1

In [ ]:
y = df.iloc[:,1]
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
df = df.iloc[:,2:]
df

,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_female,Sex_male
0,3,108.0,22.0,1,0,523.0,7.2500,146.0,2.0,0,1
1,1,190.0,38.0,1,0,596.0,71.2833,81.0,0.0,1,0
2,3,353.0,26.0,0,0,669.0,7.9250,146.0,2.0,1,0
3,1,272.0,35.0,1,0,49.0,53.1000,55.0,2.0,1,0
4,3,15.0,35.0,0,0,472.0,8.0500,146.0,2.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
886,2,548.0,27.0,0,0,101.0,13.0000,146.0,2.0,0,1
887,1,303.0,19.0,0,0,14.0,30.0000,30.0,2.0,1,0
888,3,413.0,24.0,1,2,675.0,23.4500,146.0,2.0,1,0
889,1,81.0,26.0,0,0,8.0,30.0000,60.0,0.0,0,1
890,3,220.0,32.0,0,0,466.0,7.7500,146.0,1.0,0,1

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

column_names = df.columns
data_scaled = scaler.fit_transform(df)
df_scaled = pd.DataFrame(data_scaled, columns=column_names)
df_scaled

,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_female,Sex_male
0,0.827377,-1.310217,-0.497793,0.432793,-0.473674,0.918966,-0.502445,0.449441,0.585954,-0.737695,0.737695
1,-1.566107,-0.991410,0.715048,0.432793,-0.473674,1.282625,0.786845,-1.373473,-1.942303,1.355574,-1.355574
2,0.827377,-0.357685,-0.194583,-0.474545,-0.473674,1.646283,-0.488854,0.449441,0.585954,1.355574,-1.355574
3,-1.566107,-0.672604,0.487640,0.432793,-0.473674,-1.442322,0.420730,-2.102639,0.585954,1.355574,-1.355574
4,0.827377,-1.671790,0.487640,-0.474545,-0.473674,0.664904,-0.486337,0.449441,0.585954,-0.737695,0.737695
...,...,...,...,...,...,...,...,...,...,...,...
886,-0.369365,0.400452,-0.118780,-0.474545,-0.473674,-1.183277,-0.386671,0.449441,0.585954,-0.737695,0.737695
887,-1.566107,-0.552079,-0.725201,-0.474545,-0.473674,-1.616678,-0.044381,-2.803760,0.585954,1.355574,-1.355574
888,0.827377,-0.124412,-0.346188,0.432793,2.008933,1.676173,-0.176263,0.449441,0.585954,1.355574,-1.355574
889,-1.566107,-1.415189,-0.194583,-0.474545,-0.473674,-1.646568,-0.044381,-1.962415,-1.942303,-0.737695,0.737695
890,0.827377,-0.874774,0.260233,-0.474545,-0.473674,0.635014,-0.492378,0.449441,-0.678175,-0.737695,0.737695

In [ ]:
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression# Crear un modelo de Regresión Logística
logreg = LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=1000)

# Usar RFECV para seleccionar las características
rfecv = RFECV(estimator=logreg, step=1, cv=5, scoring='accuracy')
rfecv = rfecv.fit(df_scaled, y)

# Mostrar las características seleccionadas
print('Características seleccionadas:', rfecv.support_)

# Mostrar la clasificación de las características
print('Ranking de características:', rfecv.ranking_)

# Número óptimo de características
print('Número óptimo de características :', rfecv.n_features_)

Características seleccionadas: [ True False  True  True False  True  True False  True  True  True]
Ranking de características: [1 2 1 1 3 1 1 4 1 1 1]
Número óptimo de características : 8

In [ ]:
from sklearn.model_selection import cross_val_score
column_indices = [0, 2, 3, 4, 5, 6, 7, 8, 9, -1,]
x = df_scaled.iloc[:, column_indices]
x

,Pclass,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_female,Sex_male
0,0.827377,-0.497793,0.432793,-0.473674,0.918966,-0.502445,0.449441,0.585954,-0.737695,0.737695
1,-1.566107,0.715048,0.432793,-0.473674,1.282625,0.786845,-1.373473,-1.942303,1.355574,-1.355574
2,0.827377,-0.194583,-0.474545,-0.473674,1.646283,-0.488854,0.449441,0.585954,1.355574,-1.355574
3,-1.566107,0.487640,0.432793,-0.473674,-1.442322,0.420730,-2.102639,0.585954,1.355574,-1.355574
4,0.827377,0.487640,-0.474545,-0.473674,0.664904,-0.486337,0.449441,0.585954,-0.737695,0.737695
...,...,...,...,...,...,...,...,...,...,...
886,-0.369365,-0.118780,-0.474545,-0.473674,-1.183277,-0.386671,0.449441,0.585954,-0.737695,0.737695
887,-1.566107,-0.725201,-0.474545,-0.473674,-1.616678,-0.044381,-2.803760,0.585954,1.355574,-1.355574
888,0.827377,-0.346188,0.432793,2.008933,1.676173,-0.176263,0.449441,0.585954,1.355574,-1.355574
889,-1.566107,-0.194583,-0.474545,-0.473674,-1.646568,-0.044381,-1.962415,-1.942303,-0.737695,0.737695
890,0.827377,0.260233,-0.474545,-0.473674,0.635014,-0.492378,0.449441,-0.678175,-0.737695,0.737695

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

svm = SVC()
svm_scores = cross_val_score(svm, x, y, cv=5, scoring='accuracy')
svm_scores.mean()

0.819295712761283

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=41)

modeloS = SVC()
modeloS.fit(x_train,y_train)
predicted = modeloS.predict(x_test)
predicted

array([0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0])

In [ ]:
from sklearn.metrics import accuracy_score

precision = accuracy_score(y_test, predicted)

print("Precisión:", precision)

Precisión: 0.8659217877094972

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Dividir los datos
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=41)

# Crear el modelo
modelo_gb = GradientBoostingClassifier(random_state=41)

# Entrenar el modelo
modelo_gb.fit(x_train, y_train)

# Hacer predicciones
predicted = modelo_gb.predict(x_test)

# Evaluar el modelo
precision = accuracy_score(y_test, predicted)
print("Precisión (Gradient Boosting):", precision)

Precisión (Gradient Boosting): 0.8659217877094972